Repository sylt-lang/sylt-lang, pull requests merged in 2021-03, with the labels that each got.

#101 Single-element tuples
  progs/tests/tuples.sy
  progs/tests/tuples_fail_invalid_singleton.sy
  progs/tests/tuples_fail_out_of_bounds.sy
  src/compiler.rs
  src/lib.rs
  src/vm.rs
Labels: feature/lang

#104 union types
  progs/tests/nullable_types.sy
  progs/tests/sub.sy
  progs/tests/union_types_simple.sy
  progs/tests/union_types_simple_faulty.sy
  progs/tests/wrong_params.sy
  src/compiler.rs
  src/lib.rs
  src/tokenizer.rs
  src/vm.rs
Labels: feature/lang

#115 all list tests
  progs/tests/list/args.sy
  progs/tests/list/pushing.sy
  progs/tests/list/type_faults.sy
  src/lib.rs
Labels: code-health, feature/lang

#114 type fits
  progs/tests/list/args.sy
  progs/tests/list/pushing.sy
  progs/tests/list/type_faults.sy
  src/lib.rs
  src/vm.rs
Labels: bug, code-health

#123 better blob syntax
  progs/tests/blob/cluster.sy
  progs/tests/blob/complex.sy
  progs/tests/blob/field.sy
  progs/tests/blob/field_assign.sy
  progs/tests/blob/field_get.sy
  progs/tests/blob/infer.sy
  progs/tests/blob/instantiate.sy
  progs/tests/blob/multiple_fields.sy
  progs/tests/blob/simple.sy
  src/compiler.rs
Labels: code-health, feature/lang

#119 remove parse branch
  progs/tests/tuple/fail_invalid_singleton.sy
  progs/tests/tuple/singleton.sy
  src/compiler.rs
Labels: bug, code-health

#122 sexy
  README.md
  res/sylt.png
Labels: bug, code-health, discussion, documentation, feature/compiler, feature/lang

#113 lists
  progs/tests/list/args.sy
  progs/tests/list/pushing.sy
  progs/tests/list/type_faults.sy
  progs/tests/list/types.sy
  src/compiler.rs
  src/lib.rs
  src/main.rs
  src/vm.rs
Labels: bug, code-health, feature/lang

#125 smarter indexing
  build.rs
  progs/tests/list/index_type_error.sy
  progs/tests/tuple/index_type_error.sy
  src/vm.rs
Labels: bug, code-health, feature/lang

#127 great speed
  src/compiler.rs
  src/lib.rs
  src/vm.rs
Labels: code-health

#129 Look in same directory when 'use'-ing. Also tests
  progs/tests/import/_circular_other.sy
  progs/tests/import/_other.sy
  progs/tests/import/circular_main.sy
  progs/tests/import/main.sy
  src/compiler.rs
  src/lib.rs
  src/sectionizer.rs
Labels: bug

#131 index assign
  progs/tests/blob/cluster.sy
  progs/tests/blob/complex.sy
  progs/tests/blob/faulty_num_arguments.sy
  progs/tests/blob/field_assign.sy
  progs/tests/blob/field_get.sy
  progs/tests/blob/multiple_fields.sy
  progs/tests/blob/simple.sy
  progs/tests/faulty_list_index_assign.sy
  progs/tests/list_indexing.sy
  src/compiler.rs
  src/error.rs
  src/lib.rs
  src/vm.rs
Labels: code-health, feature/lang

#137 update the flag documentation
  README.md
Labels: code-health, documentation

#141 ignore ops that cannot possible do anything
  src/lib.rs
Labels: code-health, performance

#140 Op::Force
  progs/tests/force/call.sy
  progs/tests/force/faulty_call.sy
  progs/tests/force/faulty_tuple.sy
  progs/tests/force/simple.sy
  progs/tests/force/union_call.sy
  src/compiler.rs
  src/lib.rs
  src/vm.rs
Labels: code-health, feature/lang

#138 sets and dicts
  progs/tests/constant/in_inner_functions.sy
  progs/tests/dict/empty.sy
  progs/tests/dict/mismatch_types.sy
  progs/tests/dict/returning.sy
  progs/tests/dict/simple.sy
  progs/tests/dict/type_declare.sy
  progs/tests/faulty_inner_function_type.sy
  progs/tests/set/empty.sy
  progs/tests/set/mismatch_types.sy
  progs/tests/set/returning.sy
  progs/tests/set/simple.sy
  progs/tests/set/type_declare.sy
  src/compiler.rs
  src/lib.rs
  src/sectionizer.rs
  src/vm.rs
Labels: discussion, feature/lang

#144 contains
  progs/tests/dict/contains.sy
  progs/tests/dict/faulty_contains.sy
  progs/tests/list/contains.sy
  progs/tests/list/faulty_contains.sy
  progs/tests/set/contains.sy
  progs/tests/set/faulty_contains.sy
  progs/tests/set/returning.sy
  progs/tests/set/simple.sy
  src/compiler.rs
  src/lib.rs
  src/tokenizer.rs
  src/vm.rs
Labels: code-health, feature/lang

#148 fix boolean
  progs/tests/expression/boolean_stack_order.sy
  progs/tests/for_loop/advanced_break.sy
  progs/tests/for_loop/advanced_continue.sy
  progs/tests/for_loop/loop_for.sy
  progs/tests/for_loop/simple_break.sy
  progs/tests/for_loop/simple_continue.sy
  src/compiler.rs
Labels: bug, code-health

#149 Clippy pass
  src/compiler.rs
  src/lib.rs
  src/vm.rs
Labels: code-health

#155 lingon: the awakening
  lingon/Cargo.lock
  lingon/Cargo.toml
  lingon/res/coin.png
  lingon/src/fs.glsl
  lingon/src/main.rs
  lingon/src/renderer.rs
  lingon/src/vs.glsl
  lingon/src/vs_particle.glsl
Labels: lingon

#146 iterators
  progs/tests/for_in/dict.sy
  progs/tests/for_in/empty.sy
  progs/tests/for_in/faulty_types.sy
  progs/tests/for_in/list_complex.sy
  progs/tests/for_in/loop_break.sy
  progs/tests/for_in/loop_continue.sy
  progs/tests/for_in/set.sy
  progs/tests/for_in/simple.sy
  src/compiler.rs
  src/lib.rs
  src/vm.rs
Labels: code-health, feature/compiler, feature/lang

#156 camera
  lingon/src/main.rs
  lingon/src/renderer.rs
  lingon/src/vs.glsl
  lingon/src/vs_particle.glsl
Labels: lingon

#160 documentation
  lingon/src/main.rs
  lingon/src/renderer.rs
  lingon/src/semantics.rs
Labels: documentation, lingon
