Repository sylt-lang/sylt-lang, pull requests merged in 2021-07, with the labels that each got.

#254 Number all type variants
  Cargo.lock
  sylt-common/Cargo.toml
  sylt-common/src/ty.rs
  sylt-parser/src/parser.rs
  sylt_macro/src/lib.rs
Labels: code-health

#251 Less error propogation
  Cargo.lock
  progs/tests/blob/field_get_faulty.sy
  progs/tests/dict/faulty_contains.sy
  progs/tests/ducktyping/simple_faulty.sy
  progs/tests/list/faulty_contains.sy
  progs/tests/set/faulty_contains.sy
  progs/tests/union_types_simple_faulty.sy
  sylt-common/Cargo.toml
  sylt-common/src/ty.rs
  sylt-common/src/value.rs
  sylt-parser/src/parser.rs
  sylt-typechecker/src/typechecker.rs
  sylt/build.rs
  sylt_macro/src/lib.rs
Labels: compiler internals

#257 Implicit returns
  progs/tests/implicit_return/more_lines.sy
  progs/tests/implicit_return/simple.sy
  sylt-parser/src/expression.rs
Labels: lang

#262 Is comparisons and type constants
  progs/tests/is/custom_types.sy
  progs/tests/is/simple.sy
  sylt-common/src/op.rs
  sylt-common/src/ty.rs
  sylt-compiler/src/compiler.rs
  sylt-machine/src/vm.rs
  sylt-parser/src/expression.rs
  sylt-tokenizer/src/token.rs
  sylt-typechecker/src/typechecker.rs
Labels: lang

#269 It just works!
  sylt/src/lib.rs
Labels: code-health

#264 Remove Iter
  sylt-common/src/lib.rs
  sylt-common/src/op.rs
  sylt-common/src/ty.rs
  sylt-common/src/value.rs
  sylt-machine/src/vm.rs
  sylt-std/src/sylt.rs
  sylt-typechecker/src/typechecker.rs
Labels: lang

#265 Update lingon lib
  example_game.sy
  sylt-std/src/lingon.rs
Labels: code-health

#263 loop loving
  progs/tests/looping/breaking.sy
  progs/tests/looping/continueing.sy
  progs/tests/looping/nested.sy
  sylt-compiler/src/compiler.rs
  sylt-parser/src/statement.rs
Labels: lang

#253 Allow newlines in more places
  progs/tests/blob/ambiguous_if.sy
  progs/tests/blob/faulty_num_arguments.sy
  progs/tests/blob/multiple_fields.sy
  progs/tests/blob/non_null_fields_faulty.sy
  progs/tests/blob/null_fields.sy
  progs/tests/blob/null_fields_faulty.sy
  progs/tests/blob/simple.sy
  progs/tests/faulty_list_index_assign.sy
  progs/tests/list_indexing.sy
  sylt-compiler/src/compiler.rs
  sylt-parser/src/expression.rs
  sylt-parser/src/parser.rs
  sylt-parser/src/statement.rs
Labels: lang

#274 Cleaner syntax for type constants
  progs/tests/is/simple.sy
  sylt-parser/src/expression.rs
Labels: code-health, lang

#273 if expressions 2
  progs/tests/expression/if_expressions.sy
  sylt-common/src/op.rs
  sylt-common/src/ty.rs
  sylt-compiler/src/compiler.rs
  sylt-machine/src/vm.rs
  sylt-parser/src/expression.rs
  sylt-typechecker/src/typechecker.rs
Labels: lang

#278 Better error reporting in statements
  sylt-parser/src/statement.rs
Labels: bug, lang

#277 shorthand if syntax
  progs/tests/arrow_funcs.sy
  progs/tests/if_expr_arrow.sy
  progs/tests/if_expr_short.sy
  sylt-common/src/block.rs
  sylt-common/src/op.rs
  sylt-compiler/src/compiler.rs
  sylt-machine/src/vm.rs
  sylt-parser/src/expression.rs
  sylt-parser/src/parser.rs
  sylt-parser/src/statement.rs
  sylt-typechecker/src/typechecker.rs
  sylt/src/lib.rs
Labels: lang

#279 Do some spring cleaning and remove unsed files
  benches/sylt_benchmark.rs
  coverage.sh
  res/bloop.wav
  res/coin.png
  res/example_game.sy
Labels: code-health

#280 Is-statemnts
  progs/tests/is/compile_time.sy
  progs/tests/is/compile_time_different.sy
  progs/tests/is/faulty_checking.sy
  sylt-compiler/src/compiler.rs
  sylt-parser/src/statement.rs
Labels: lang

#281 More complex typechecking
  progs/tests/func/wrong_params.sy
  progs/tests/is/compile_time.sy
  progs/tests/is/compile_time_different.sy
  progs/tests/is/complex_structures.sy
  progs/tests/is/faulty_complex.sy
  sylt-common/src/ty.rs
  sylt-compiler/src/compiler.rs
Labels: lang
