Repository sylt-lang/sylt-lang, pull requests merged in 2021-05, with the labels that each got.

#178 Add camera controls!
  example_game.sy
  src/lingon_sylt.rs
Labels: lingon

#177 Lingon audio linking
  Cargo.lock
  bloop.wav
  example_game.sy
  src/lingon_sylt.rs
Labels: lingon

#197 Add more standard lib functions
  src/lib_sylt.rs
  src/lingon_sylt.rs
Labels: lingon

#199 Fix compiler crash with unknown fields on blobs
  progs/tests/blob/field_get_faulty.sy
  src/typechecker.rs
  src/vm.rs
Labels: bug

#200 Better macros
  src/lib.rs
  src/lib_sylt.rs
  src/lingon_sylt.rs
  sylt_macro/src/lib.rs
Labels: P-1

#198 link functions when deserializing
  src/error.rs
  src/lib.rs
  src/main.rs
Labels: bug

#203 Add instructions for getting started
  README.md
Labels: documentation

#206 Build doc on CI
  .github/workflows/rust.yml
Labels: documentation
